In [3]:
import os
import pandas as pd
import numpy as np

import sys
#custom libraries
sys.path.append("/cluster/bh0085/mybio")

#allows import of ipnb notebooks in dev mode
import ipnb_utils
from _config import EXP_DESIGN_2955, EXP_DESIGN_2901

In [32]:
import subprocess as spc
spc.call("wc -l ")

num_tot = 0
num_bad_q = 0
fname1 = "/cluster/bh0085/shortreads/SHE2955_UPDATED/Data/Intensities/BaseCalls/Undetermined_AH3W5GBGX9_S0_L001_R1_001.fastq"
fname2 = "/cluster/bh0085/shortreads/SHE2955_UPDATED/Data/Intensities/BaseCalls/Undetermined_AH3W5GBGX9_S0_L001_R2_001.fastq"

i = -1

with open(fname1) as f1:
  with open(fname2) as f2:
    while 1:
      i+= 1
      try:
          l1 = f1.next()
          l2 = f2.next()
      except EOFError, e:
          break
            
      if i > 20: break
            
      #if i % 1000000 ==0: 
      #   print i / 1000000
      if i % 4 == 0:
            header1 = l1.strip()
            header2 = l2.strip()
      if i % 4 == 1:
            read1 = l1.strip()
            read2 = l2.strip()
      if i % 4 == 3:
            num_tot += 1
            markbad = 0
            for l in [l1,l2]:
                qs = l.strip()
                quals = [ord(s)-33 for s in qs]
                if np.mean(quals) < 30:
                  num_bad_q += 1
                  markbad = 1
                  break
            
            print read2
            print header1
            
            i7 = header1[-17:-9]
            i5 = header1[-8:]
            
            match = EXP_DESIGN_2955.loc[(EXP_DESIGN_2955["i7 Index reads"]==i7) * (EXP_DESIGN_2955["i5 Index reads"]==i5)]

            if len(match == 1):
                
            
            if markbad: continue

CGCTCACTGAAATTGT
@NS500413:513:H3W5GBGX9:1:11101:2253:1057 1:N:0:TCCGCGAA+GCCTCTAT
1
GCCTCTAT TCCGCGAA
GATAGGAAATAGTGAT
@NS500413:513:H3W5GBGX9:1:11101:5731:1057 1:N:0:TCCGCGAA+GCCTCTAT
1
GCCTCTAT TCCGCGAA
CGCCTCTTACATCCGT
@NS500413:513:H3W5GBGX9:1:11101:2065:1057 1:N:0:TAATGCGC+AGGCTATA
0
AGGCTATA TAATGCGC
TCCTACCACTCATATT
@NS500413:513:H3W5GBGX9:1:11101:11225:1057 1:N:0:CGGCTATG+GCCTCTAT
1
GCCTCTAT CGGCTATG
GAGCCTAAATAGTGAT
@NS500413:513:H3W5GBGX9:1:11101:16377:1057 1:N:0:CTGAACTA+GCCTCTAT
0
GCCTCTAT CTGAACTA

In [34]:
EXP_DESIGN_2955.loc[(EXP_DESIGN_2955["i5 Index reads"]==i5) ]

,Name,i7 Index reads,i5 Index reads,Replicate,Type,Celltype,Library,Technical name
4,DLD1_WT_BR1,CTGAAGCT,GCCTCTAT,1,GFP,DLD1,STARR_Seq,na
5,DLD1_WT_BR2,TAATGCGC,GCCTCTAT,2,GFP,DLD1,STARR_Seq,na
6,U2OS_WT_BR1,CGGCTATG,GCCTCTAT,1,GFP,U2OS,STARR_Seq,na
7,U2OS_WT_BR2,TCCGCGAA,GCCTCTAT,2,GFP,U2OS,STARR_Seq,na